<<<<<<< HEAD
--- 
     - hosts: localhost
       gather_facts: true
       become: true
       roles: 
        - { role: docker }
=======
---

- hosts: localhost
  gather_facts: true
  become: true
  become_user: nourane
  roles:
    - { role: docker }
>>>>>>> d53dfeccfd158af4924845f13be4b99651c144b3

